Repository Team-Coverflow/Coverflow-FE, pull requests merged in 2024-04, with the labels that each got.

#227 [Featrure] 메인 페이지 및 마이페이지 UI 개선
  src/asset/image/back.svg
  src/asset/image/clock.svg
  src/asset/image/home.svg
  src/asset/image/tab_logo.svg
  src/asset/sass/etc/header/sideBar.scss
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/myPage/infoEditPage.scss
  src/components/NotFoundPage.tsx
  src/components/global/utils/eventApiUtils.js
  src/components/ui/contactSlider/contactSlider.scss
Labels: UI

#229 [bugfix] 실시간 알림 수정
  src/asset/image/feedback.svg
  src/asset/sass/etc/header/sideBar.scss
  src/components/global/utils/eventApiUtils.js
  src/components/ui/adminSelection/companyDetail.tsx
  src/globalStyles.js
Labels: BugFix

#230 [bugfix] 실시간 알림 수정
  src/components/global/utils/eventApiUtils.js
Labels: BugFix

#231 [bugfix] 실시간 알림 수정
  src/components/global/utils/eventApiUtils.js
Labels: BugFix

#228 fetchAPI, UI 수정
  src/asset/sass/etc/question/answer.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/question/answer.jsx
  src/components/ui/question/answer.tsx
  src/components/ui/searchInput/searchInput.tsx
Labels: BugFix, Feature

#233 Bugfix/#232 admin data process improvement
  src/components/global/utils/eventApiUtils.js
  src/components/ui/adminSelection/adminPagination.tsx
  src/components/ui/adminSelection/companyDetail.tsx
  src/components/ui/adminSelection/companySelection.tsx
  src/components/ui/button/Button/Button.jsx
Labels: BugFix

#237 [Feature] 마이페이지 CSS 추가
  src/components/pages/myPage/myPage.tsx
Labels: UI

#239 Feature/#266 alpha UI improvement
  src/asset/sass/etc/header/sideBar.scss
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/etc/inputBox/textArea.scss
  src/asset/sass/pages/myPage/feedbackPage.scss
  src/asset/sass/pages/myPage/myPage.scss
  src/components/pages/loginPage/loginPage.tsx
  src/components/ui/myPageSelection/myComponent.scss
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/tabBar/tabBar.tsx
Labels: BugFix, UI

#240 Bugfix: 클릭 시 검색 안되는 오류 및 검색 후 재검색 로직 수정
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/searchInput/searchInput.tsx
Labels: BugFix

#241 [Bugfix] 비로그인 시 검색 가능하도록 수정
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/searchInput/searchInput.tsx
Labels: BugFix

#246 [bugfix] 실시간 알림 버그 수정
  package-lock.json
  package.json
  src/App.js
  src/asset/image/notification-adopt.svg
  src/asset/image/notification-answer.svg
  src/asset/image/notification-fishbun.svg
  src/asset/image/notification-question.svg
  src/asset/image/tabbar-new-alert.svg
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/eventApiUtils.js
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/termsPage/termsPage.tsx
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/tabBar/tabBar.tsx
  src/store/actions/alertActions.js
  src/store/actions/type.js
  src/store/alertReducer.js
  src/store/index.js
  yarn.lock
Labels: BugFix

#247 bugfix 토큰 불러올 때 발생하는 훅 에러 수정합니다.
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#248 bugfix 핸들러 function 변경으로 인한 토큰 발급 로직 에러 수정합니다.
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#249 bugfix 실시간 알림 버그 수정
  src/asset/sass/etc/tabBar/tabBar.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/eventApiUtils.js
Labels: BugFix

#236 Feat : 신고 팝업 띄우기, 기업 상세 페이지에서 뒤로 가기 버튼 클릭 시 오류나는 부분 수정
  src/asset/image/dots-vertical.svg
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/question/question.tsx
  src/components/ui/searchInput/searchInput.tsx
  yarn.lock
Labels: Feature

#252 질문 상세 페이지 작업
  src/asset/image/trophy.svg
  src/asset/sass/etc/question/answer.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/question/answer.tsx
  yarn.lock
Labels: Feature, UI

#254 (#195)feat: 실시간 알림 확인 기능 추가합니다.
  src/asset/sass/pages/notificationPage/notificationList.scss
  src/asset/sass/pages/notificationPage/notificationPage.scss
  src/components/global/utils/eventApiUtils.js
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
Labels: API, UI

#255 bugfix 실시간 알림 기능 확인을 위한 테스트 로그 추가합니다.
  src/asset/sass/etc/tabBar/tabBar.scss
  src/components/global/token/tokenManagement.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/tabBar/tabBar.tsx
Labels: BugFix

#256 실시간 알림 기능 확인을 위한 테스트 로그 추가합니다.
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#257 실시간 알림 기능 확인을 위한 테스트 로그 추가합니다.
  src/components/global/token/tokenManagement.jsx
  src/components/ui/header/userInfoHeader.jsx
Labels: BugFix

#258 bugfix 실시간 알림 확인 콘솔 제거 및 에러 해결
  src/asset/image/plus.svg
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/global/utils/eventApiUtils.js
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/adminSelection/companySelection.tsx
  src/components/ui/searchInput/searchInput.tsx
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/tabBar/tabBar.tsx
Labels: BugFix, UI

#259 feat : 답변 채택 인지
  src/components/ui/question/answer.tsx
Labels: Feature

#260 bugfix 실시간 알림 코드 수정합니다.
  package.json
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/eventApiUtils.js
  src/components/pages/myPage/myPage.tsx
  src/components/pages/premiumPage/NotFound.jsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/pages/termsPage/termsPage.tsx
  src/components/ui/adminSelection/adminPagination.tsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/selectSlider/selectSlider.tsx
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/tabBar/tabBar.tsx
  src/index.css
  src/styledComponent.js
Labels: API, BugFix, UI, Settings

#262 [Style] UI 개선 피드백 적용했습니다.
  src/asset/image/home.svg
  src/asset/image/warning.svg
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/notificationPage/notificationList.scss
  src/asset/sass/pages/notificationPage/notificationPage.scss
  src/components/pages/myPage/myPage.tsx
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactList.scss
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/contactSlider/contactSlider.scss
Labels: UI

#264 공지사항 UI 수정합니다.
  src/asset/image/notice-down-arrow.svg
  src/asset/image/notice-up-arrow.svg
  src/asset/sass/pages/myPage/noticePage.scss
  src/components/global/utils/eventApiUtils.js
  src/components/pages/myPage/noticePage.tsx
Labels: BugFix, UI

#265 답변 및 질문 상세 페이지 UI 수정
  src/asset/sass/etc/question/answer.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/question/answer.tsx
  yarn.lock
Labels: BugFix, Feature, UI

#267 공지사항, 공통 UI 수정했습니다.
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/myPage/noticePage.scss
  src/components/NotFoundPage.tsx
  src/components/global/utils/apiUtil.js
  src/components/global/utils/eventApiUtils.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/feedbackPage.tsx
  src/components/pages/myPage/infoEditPage.tsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/myPage/noticePage.tsx
  src/components/pages/myPage/secessionPage.tsx
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/adminSelection/adminSideTap.tsx
  src/components/ui/adminSelection/companyDetail.tsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myQuestion.tsx
  src/components/ui/question/answer.tsx
  src/components/ui/searchInput/searchInput.tsx
  src/components/ui/selectSlider/selectSlider.tsx
  src/hooks/errorBoundary.tsx
  src/router/allRouter.js
Labels: API, BugFix, UI

#269 Revert "공지사항, 공통 UI 수정했습니다."
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/myPage/noticePage.scss
  src/components/NotFoundPage.tsx
  src/components/global/utils/apiUtil.js
  src/components/global/utils/eventApiUtils.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/feedbackPage.tsx
  src/components/pages/myPage/infoEditPage.tsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/myPage/noticePage.tsx
  src/components/pages/myPage/secessionPage.tsx
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/adminSelection/adminSideTap.tsx
  src/components/ui/adminSelection/companyDetail.tsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myQuestion.tsx
  src/components/ui/question/answer.tsx
  src/components/ui/searchInput/searchInput.tsx
  src/components/ui/selectSlider/selectSlider.tsx
  src/hooks/errorBoundary.tsx
  src/router/allRouter.js
Labels: BugFix

#270 버그 수정
  src/asset/image/chat2.svg
  src/asset/image/graph_bar.svg
  src/asset/image/justice.svg
  src/asset/image/search.svg
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/etc/question/question.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/ui/question/answer.tsx
  src/components/ui/question/question.tsx
Labels: BugFix, Feature, UI

#272 (#271)bugfix: 실시간 알림 연동 되도록 수정했습니다.
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/eventApiUtils.js
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/termsPage/termsPage.tsx
Labels: BugFix

#274 [Bugfix] 스타일 수정
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/components/NotFoundPage.tsx
  src/components/pages/notificationPage/notificationList.jsx
  src/components/ui/selectSlider/selectSlider.tsx
  src/hooks/errorBoundary.tsx
  src/router/allRouter.js
Labels: UI

#276 알림 페이지 무한 스크롤 적용했습니다.
  src/components/global/constants/index.ts
  src/components/global/utils/eventApiUtils.js
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/contactSlider/disclaimer.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myQuestion.tsx
Labels: Feature

#275 답변 못 불러오는 오류 수장, 필터링 된 질문 카운트
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/ui/question/question.tsx
  src/components/ui/searchInput/searchInput.tsx
Labels: Feature, UI
