Repository Team-Coverflow/Coverflow-FE, pull requests merged in 2024-03, with the labels that each got.

#146 [Feature] 문의 페이지 API 연결했습니다.
  package.json
  src/components/global/constants/index.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactList.scss
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/contactSlider/contactSlider.scss
Labels: API

#148 [Bugfix] API 주소 수정
  package.json
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/question/answerContainer.jsx
  src/components/ui/searchInput/searchInput.jsx
Labels: BugFix

#149 [BugFix] - 변경된 API 주소 확인
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/searchInput/searchInput.jsx
Labels: BugFix

#150 [Feature] 공지사항 페이지 Pagination 추가 기능
  src/asset/sass/pages/myPage/noticePage.scss
  src/components/pages/myPage/noticePage.jsx
Labels: Feature, UI

#153 (COFLLL#144) feat : 상점 페이지 구현했습니다.
  src/asset/image/faceicon.svg
  src/asset/sass/etc/selection/fishListItem.scss
  src/asset/sass/pages/storePage/storePage.scss
  src/components/pages/storePage/storePage.jsx
  src/components/ui/banner/currentFishBanner.jsx
  src/components/ui/banner/currentFishBanner.scss
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/selectSlider/selectSlider.jsx
  src/components/ui/selection/fishListItem.jsx
Labels: UI

#152 (COFLLL#151) feat : 검색 디바운스 적용했습니다.
  src/components/ui/searchInput/searchInput.jsx
  src/hooks/useDebounce.js
Labels: Feature

#156 [Feature] - 문의 페이지 수정했습니다.
  package.json
  src/asset/image/check_payment.svg
  src/asset/sass/etc/button/Button.scss
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/completePaymentPage/completePaymentPage.scss
  src/asset/sass/pages/termsPage/termsPage.jsx
  src/components/global/token/tokenManagement.jsx
  src/components/pages/completePaymentPage/completePaymentPage.jsx
  src/components/ui/button/Button/Button.jsx
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactList.scss
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/genderSelection/genderSelection.jsx
  src/components/ui/genderSelection/genderSelection.scss
  src/components/ui/tabBar/tabBar.jsx
  src/router/allRouter.js
  yarn.lock
Labels: UI

#163 [hotfix] 토큰 받아오는 페이지 수정중입니다.
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#169 [Feat] 기업 검색 결과 노출, 유틸 함수 작성
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/searchInput/searchInput.jsx
  src/index.js
  src/utils/utils.js
Labels: Feature, Settings

#173 [Feature] 붕어빵 개수 반영
  src/components/pages/postPage/questionWritePage.jsx
  src/components/ui/selection/fishTag.jsx
Labels: BugFix, Feature

#171 [Feature] CSS 및 로직 리팩토링
  src/asset/sass/pages/myPage/noticePage.scss
  src/asset/sass/pages/myPage/premiumPage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/asset/sass/pages/searchPage/companyRegistPage.scss
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/searchInput/searchInput.jsx
  src/utils/utils.js
Labels: Feature

#174 [Feature] 피드백 페이지 및 부가 페이지 추가
  src/asset/image/feedback.svg
  src/asset/image/notice.svg
  src/asset/image/premium.svg
  src/asset/image/sideevent.svg
  src/asset/image/sidenotice.svg
  src/asset/image/store.svg
  src/asset/image/tab_logo.svg
  src/asset/sass/etc/button/Button.scss
  src/asset/sass/etc/header/header.scss
  src/asset/sass/etc/header/sideBar.scss
  src/asset/sass/etc/inputBox/textArea.scss
  src/asset/sass/pages/myPage/feedbackPage.scss
  src/components/global/constants/index.js
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/myPage/feedbackPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/termsPage/termsPage.jsx
  src/components/ui/button/Button/Button.jsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/header.jsx
  src/components/ui/header/sideBar.jsx
  src/components/ui/inputbox/TextArea.jsx
  src/components/ui/inputbox/input.jsx
  src/router/allRouter.js
  src/store/actions/authActions.js
  src/store/actions/type.js
  src/store/authReducer.js
  src/store/index.js
Labels: Feature, UI

#176 [Feature] 리프레쉬 토큰 타이머 포함한 api 훅 테스트합니다.
  src/components/global/utils/apiUtil.js
  src/components/ui/contactSlider/contactSlider.jsx
Labels: API

#177 [Bugfix] API 핸들러 수정합니다.
  src/components/global/utils/apiUtil.js
  src/components/ui/contactSlider/contactSlider.jsx
Labels: BugFix

#178 [Bugfix] API 핸들러 수정합니다.
  src/components/global/utils/apiUtil.js
  src/components/ui/contactSlider/contactSlider.jsx
Labels: BugFix

#179 [Bugfix] API 핸들러 수정합니다.
  src/components/ui/contactSlider/contactSlider.jsx
Labels: BugFix

#180 [Bugfix] Redux dispatch 로직 수정합니다.
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
Labels: BugFix

#181 [Bugfix] Redux dispatch 로직 수정합니다.
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
Labels: BugFix

#184 [Bugfix] API 요청 핸들러 수정합니다.
  src/asset/image/left_arrow.svg
  src/asset/image/right_arrow.svg
  src/components/global/utils/apiUtil.js
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactSlider.jsx
Labels: BugFix

#186 [Bugfix] API 요청 헤더 수정합니다.
  src/components/global/utils/apiUtil.js
Labels: BugFix

#187 [Bugfix] API 명세에 맞게 일부 코드 수정합니다.
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactSlider.jsx
Labels: BugFix

#183 [UI] Pagination 컴포넌트 테스트 및 로직 수정
  src/components/pages/myPage/noticePage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/Pagination.jsx
  src/components/ui/searchInput/searchInput.jsx
Labels: Feature, UI

#194 [bugfix] 사이드 바 스타일 수정했습니다.
  src/asset/sass/etc/header/sideBar.scss
Labels: BugFix, UI

#190 [Feat] 토스트 추가, 데이터 프로퍼티 수정, styled-components 관련 수정입니다.
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/ui/question/question.jsx
Labels: BugFix, Feature

#197 (COFLLL#195) feat : 실시간 알림 테스트입니다.
  src/components/pages/mainPage/mainPage.jsx
Labels: API, Feature

#198 [Feature] 데이터 프로퍼티 변경 및 필요없는 코드 삭제
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
Labels: API, Feature

#199 [Feature] 타입스크립트 마이그레이션합니다.
  src/asset/image/fingerprint.svg
  src/components/global/constants/index.ts
  src/components/pages/loginPage/loginPage.tsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/myPage/eventPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/myPage/noticePage.jsx
  src/components/pages/myPage/secessionPage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/pages/searchPage/searchPage.tsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/pages/storePage/storePage.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/banner/currentFishBanner.tsx
  src/components/ui/header/titleHeader.jsx
  src/components/ui/header/titleHeader.tsx
  src/components/ui/question/question.jsx
  src/components/ui/searchInput/searchInput.jsx
  src/components/ui/selectSlider/selectSlider.tsx
  src/components/ui/selection/fishListItem.tsx
  src/components/ui/selection/fishTag.tsx
  src/components/ui/tabBar/tabBar.tsx
  src/router/allRouter.js
  src/styledComponent.ts
  src/types/image.d.ts
  tsconfig.json
Labels: Feature, Settings

#200 [UI] 질문 등록 페이지 및 질문 상세 페이지 UI 수정했습니다.
  .eslintrc.js
  src/asset/image/chaticon.svg
  src/asset/image/group.svg
  src/asset/image/money.svg
  src/asset/image/nature-ecology-tree-3--tree-plant-cloud-shape-park.svg
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/etc/selection/fishTag.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/myPage/contactPage.jsx
  src/components/pages/myPage/feedbackPage.jsx
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/searchPage.tsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/question/answerContainer.jsx
  src/components/ui/searchInput/searchInput.tsx
  src/components/ui/selectSlider/selectSlider.tsx
  src/components/ui/selection/fishTag.tsx
  src/hooks/useDebounce.ts
  src/router/allRouter.js
  src/utils/utils.js
  src/utils/utils.ts
Labels: UI

#202 [Feature] 전체 오류 검사 및 수정했습니다.
  .eslintrc.js
  package.json
  src/asset/image/back.svg
  src/asset/image/edit.svg
  src/asset/image/notice.svg
  src/asset/image/premium.svg
  src/asset/image/store.svg
  src/asset/sass/etc/header/sideBar.scss
  src/asset/sass/etc/header/titleHeader.scss
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/myPage/myPage.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/contactPage.jsx
  src/components/pages/myPage/eventPage.jsx
  src/components/pages/myPage/feedbackPage.jsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/myPage/secessionPage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/pages/storePage/storePage.tsx
  src/components/pages/termsPage/termsPage.jsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/titleHeader.tsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/question/answer.jsx
  src/components/ui/question/question.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/tabBar/tabBar.tsx
  src/globalStyles.js
  src/router/allRouter.js
  src/styledComponent.js
  src/styledComponent.ts
  src/utils/utils.ts
  tsconfig.json
  yarn.lock
Labels: BugFix

#203 [UI] 메인페이지 UI 수정 작업 진행했습니다.
  src/asset/image/banner.svg
  src/asset/image/chaticon.png
  src/asset/image/chaticon.svg
  src/asset/image/clock.svg
  src/asset/image/home.svg
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/myPage/premiumPage.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/NotFoundPage.tsx
  src/components/WIL.tsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/premiumPage/premiumPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/pages/storePage/storePage.tsx
  src/components/ui/banner/bannerImage.scss
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/searchInput/searchInput.tsx
  src/router/allRouter.js
Labels: UI

#205 [Feature] 관리자 페이지 구현했습니다.
  src/asset/image/admin-answer.svg
  src/asset/image/admin-comment.svg
  src/asset/image/admin-company.svg
  src/asset/image/admin-contact.svg
  src/asset/image/admin-logo.svg
  src/asset/image/admin-notice.svg
  src/asset/image/admin-question.svg
  src/asset/image/admin-report.svg
  src/asset/image/admin-search.svg
  src/asset/image/admin-toggle.svg
  src/asset/image/admin-user.svg
  src/asset/sass/etc/button/Button.scss
  src/asset/sass/pages/adminPage/adminMainPage.scss
  src/components/global/constants/companyOption.ts
  src/components/pages/adminPage/adminMainPage.jsx
  src/components/pages/adminPage/adminMainPage.tsx
  src/components/ui/adminSelection/adminPagination.tsx
  src/components/ui/adminSelection/adminSideTap.scss
  src/components/ui/adminSelection/adminSideTap.tsx
  src/components/ui/adminSelection/companyDetail.tsx
  src/components/ui/adminSelection/companySelection.scss
  src/components/ui/adminSelection/companySelection.tsx
  src/components/ui/adminSelection/feedbackSelection.tsx
  src/components/ui/button/Button/Button.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/router/allRouter.js
  tsconfig.json
Labels: API, Feature, UI

#204 [UI] 기업 등록 페이지 및 메인 페이지 UI 수정
  src/asset/sass/etc/inputBox/textArea.scss
  src/asset/sass/etc/selection/fishTag.scss
  src/asset/sass/pages/loginPage/loginPage.scss
  src/asset/sass/pages/loginPage/nicknamePage.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/myPage/noticePage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/asset/sass/pages/searchPage/companyRegistPage.scss
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/pages/searchPage/companyRegistPage.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/genderSelection/genderSelection.jsx
  src/components/ui/genderSelection/genderSelection.scss
  src/components/ui/searchInput/searchInput.tsx
  src/router/allRouter.js
Labels: UI

#207 (#206)bugfix: 로그아웃 로직 수정합니다.
  src/components/pages/myPage/myPage.tsx
  src/components/ui/adminSelection/adminSideTap.tsx
  src/components/ui/header/userInfoHeader.jsx
Labels: BugFix

#209 [feature] 피드백, 로그아웃 API 연결했습니다.
  src/asset/image/secesstionComplete.svg
  src/asset/sass/pages/myPage/secessionPage.scss
  src/components/global/token/tokenManagement.jsx
  src/components/pages/myPage/feedbackPage.jsx
  src/components/pages/myPage/secessionCompletePage.tsx
  src/components/pages/termsPage/terms.js
  src/components/pages/termsPage/termsPage.jsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/toast/toast.tsx
  src/router/allRouter.js
Labels: API

#214 [Bugfix] 알림 연결 수정했습니다.
  src/components/global/token/tokenManagement.jsx
  src/components/pages/termsPage/termsPage.jsx
  src/types/event-source-polyfill.d.ts
Labels: BugFix

#212 bugfix : 동의 체크 클릭 시 결제하기 버튼 활성화 되도록 수정했습니다.
  src/asset/image/warning-triangle.svg
  src/asset/sass/pages/myPage/premiumPage.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/pages/myPage/myPage.tsx
  src/components/pages/premiumPage/premiumPage.jsx
  src/components/pages/premiumPage/premiumPage.tsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/searchInput/searchInput.tsx
  src/router/allRouter.js
Labels: BugFix, UI

#215 [UI] UI 수정, node-sass 관련 문제 테스트
  package.json
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/companyRegistPage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/searchInput/searchInput.tsx
  src/utils/utils.ts
  yarn.lock
Labels: BugFix, UI

#216 [Bugfix] 알파테스트 중 발생한 오류 수정합니다.
  src/asset/image/allCheck_green.svg
  src/asset/image/allCheck_grey.svg
  src/asset/image/faceicon.svg
  src/asset/image/reward.svg
  src/asset/image/toast-error.svg
  src/asset/image/toast-success.svg
  src/asset/sass/etc/inputBox/textArea.scss
  src/asset/sass/pages/myPage/infoEditPage.scss
  src/asset/sass/pages/storePage/storePage.scss
  src/asset/sass/pages/termsPage/termsPage.scss
  src/components/global/constants/privateRoute.tsx
  src/components/global/token/tokenManagement.jsx
  src/components/pages/myPage/contactPage.jsx
  src/components/pages/myPage/feedbackPage.jsx
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/storePage/storePage.tsx
  src/components/pages/termsPage/terms.js
  src/components/pages/termsPage/termsPage.jsx
  src/components/ui/adminSelection/companySelection.tsx
  src/components/ui/banner/currentFishBanner.scss
  src/components/ui/banner/currentFishBanner.tsx
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/contactSlider/contactSlider.scss
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myComponent.scss
  src/components/ui/myPageSelection/myQuestion.tsx
  src/components/ui/toast/toast.tsx
  src/router/allRouter.js
  src/utils/utils.ts
Labels: BugFix, Feature, UI

#218 [UI] 기업 상세 페이지 UI 수정
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/components/ui/question/question.tsx
  src/components/ui/toast/toast.tsx
Labels: UI

#219 [Bugfix] 알파테스트 시 발생한 버그 및 UI 수정
  package.json
  src/App.js
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/myPage/myPage.scss
  src/components/global/utils/apiUtil.js
  src/components/pages/myPage/feedbackPage.jsx
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/myPage/secessionPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/termsPage/termsPage.jsx
  src/components/ui/adminSelection/adminPagination.tsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myComponent.scss
  src/components/ui/myPageSelection/myQuestion.tsx
  src/hooks/errorBoundary.tsx
  src/router/allRouter.js
  yarn.lock
Labels: API, BugFix, Feature, UI

#221 [Bugfix] 알파테스트 버그 수정
  src/asset/image/banner.svg
  src/asset/image/secessionWarning.svg
  src/asset/image/secesstion-toggle.svg
  src/asset/sass/etc/selection/secessionSelection.scss
  src/asset/sass/pages/myPage/premiumPage.scss
  src/asset/sass/pages/myPage/secessionPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/myPage/feedbackPage.jsx
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/myPage/secessionPage.jsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/premiumPage/premiumPage.jsx
  src/components/pages/premiumPage/premiumPage.tsx
  src/components/pages/premiumPage/premiumTicket.jsx
  src/components/pages/premiumPage/premiumTicket.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/pages/searchPage/searchPage.tsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/adminSelection/adminSideTap.tsx
  src/components/ui/adminSelection/companyDetail.tsx
  src/components/ui/banner/bannerImage.jsx
  src/components/ui/banner/bannerImage.scss
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myQuestion.tsx
  src/components/ui/selection/secessionSelection.jsx
Labels: API, BugFix, Feature, UI

#223 [Feature] 필요없는 파일 제거 및 로직 수정
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/premiumPage/premiumPage.jsx
  src/components/pages/premiumPage/premiumTicket.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/ui/question/question.tsx
  src/router/allRouter.js
  yarn.lock
Labels: BugFix, Feature

#222 [Bugfix] 알파테스트 UI 오류 수정
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/toast/toast.tsx
Labels: UI

#224 [Feature] 검색 결과 기능 수정 및 질문 작성 페이지 UI 수정
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/adminSelection/companyDetail.tsx
  src/components/ui/question/question.jsx
  src/components/ui/searchInput/searchInput.tsx
Labels: BugFix, Feature, UI
