Repository Team-Coverflow/Coverflow-FE, pull requests merged in 2024-01, with the labels that each got.

#3 chore : PR템플릿 적용했습니다.
  .github/ISSUE_TEMPLATE/issue--✨feature.md
  .github/ISSUE_TEMPLATE/issue--🐞bugfix.md
  .github/pull_request_template.md
  .github/workflows/github-actions.yml
Labels: Settings

#5 (#4)feat : 파비콘 변경했습니다.
  public/cflogos.png
  public/index.html
Labels: UI

#9 [Feature] - ESlint & Prettier 설정했습니다.
  .eslintrc.js
  .prettierrc
  .vscode/setting.json
  package.json
  yarn.lock
Labels: Settings

#11 [Feature] - 스타일 전역 설정했습니다.
  package.json
  public/index.html
  src/App.js
  src/font/SpoqaHanSansNeo-Bold.woff
  src/font/SpoqaHanSansNeo-Light.woff
  src/font/SpoqaHanSansNeo-Medium.woff
  src/font/SpoqaHanSansNeo-Regular.woff
  src/font/SpoqaHanSansNeo-Thin.woff
  src/font/font.css
  src/globalStyles.js
  src/index.js
  yarn.lock
Labels: Settings

#14 [Feature] 메인 헤더 구현했습니다.
  .babelrc
  .eslintrc.js
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/asset/sass/etc/header/header.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/components/pages/mainPage/mainPage.jsx
  src/components/ui/header/header.jsx
  src/font/SpoqaHanSansNeo-Bold.ttf
  src/font/SpoqaHanSansNeo-Light.ttf
  src/font/SpoqaHanSansNeo-Medium.ttf
  src/font/SpoqaHanSansNeo-Regular.ttf
  src/font/SpoqaHanSansNeo-Thin.ttf
  src/font/font.css
  src/globalStyles.js
  src/router/allRouter.js
  src/webpack.config.js
  yarn.lock
Labels: BugFix, Feature, UI, Settings

#16 [Feature] - 메인 페이지 구현했습니다.
  .eslintrc.js
  package.json
  public/index.html
  src/App.js
  src/asset/image/alarmicon.svg
  src/asset/image/back.svg
  src/asset/image/google.svg
  src/asset/image/hambar.svg
  src/asset/image/kakao.svg
  src/asset/image/logo.svg
  src/asset/image/naver.svg
  src/asset/image/searchicon.svg
  src/asset/image/usericon.svg
  src/asset/sass/etc/header/header.scss
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/loginPage/loginPage.scss
  src/asset/sass/pages/loginPage/nicknamePage.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/ui/header/header.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/font/Pretendard-Black.woff
  src/font/Pretendard-Bold.woff
  src/font/Pretendard-ExtraBold.woff
  src/font/Pretendard-ExtraLight.woff
  src/font/Pretendard-Light.woff
  src/font/Pretendard-Medium.woff
  src/font/Pretendard-Regular.woff
  src/font/Pretendard-SemiBold.woff
  src/font/Pretendard-Thin.woff
  src/font/SpoqaHanSansNeo-Bold.ttf
  src/font/SpoqaHanSansNeo-Bold.woff
  src/font/SpoqaHanSansNeo-Light.ttf
  src/font/SpoqaHanSansNeo-Light.woff
  src/font/SpoqaHanSansNeo-Medium.ttf
  src/font/SpoqaHanSansNeo-Medium.woff
  src/font/SpoqaHanSansNeo-Regular.ttf
  src/font/SpoqaHanSansNeo-Regular.woff
  src/font/SpoqaHanSansNeo-Thin.ttf
  src/font/SpoqaHanSansNeo-Thin.woff
  src/font/font.css
  src/fontAwesome.jsx
  src/globalStyles.js
  src/router/allRouter.js
  yarn.lock
Labels: Feature, UI

#19 [Feature] - 로그인, 회원 정보 설정 페이지 구현했습니다.
  package.json
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/loginPage/loginPage.scss
  src/asset/sass/pages/loginPage/nicknamePage.scss
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/index.js
  yarn.lock
Labels: Feature, UI

#22 [Feature] - 네비게이션 탭 바 수정 및 리액트 운영 환경 배포
  .github/workflows/github-actions-front.yml
  .github/workflows/github-actions.yml
  Dockerfile-front-prod
  src/components/pages/mainPage/mainPage.jsx
  src/components/ui/tabBar/tabBar.jsx
Labels: Feature, Settings

#23 [Feature] - React App 운영 환경 배포했습니다.
  .babelrc
  .eslintrc.js
  .github/ISSUE_TEMPLATE/issue--✨feature.md
  .github/ISSUE_TEMPLATE/issue--🐞bugfix.md
  .github/pull_request_template.md
  .github/workflows/github-actions-front.yml
  .prettierrc
  .vscode/setting.json
  Dockerfile-front-prod
  README.md
  package-lock.json
  package.json
  public/cflogos.png
  public/index.html
  src/App.js
  src/asset/image/alarmicon.svg
  src/asset/image/back.svg
  src/asset/image/google.svg
  src/asset/image/hambar.svg
  src/asset/image/kakao.svg
  src/asset/image/logo.svg
  src/asset/image/naver.svg
  src/asset/image/searchicon.svg
  src/asset/image/usericon.svg
  src/asset/sass/etc/header/header.scss
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/loginPage/loginPage.scss
  src/asset/sass/pages/loginPage/nicknamePage.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/ui/header/header.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/font/Pretendard-Black.woff
  src/font/Pretendard-Bold.woff
  src/font/Pretendard-ExtraBold.woff
  src/font/Pretendard-ExtraLight.woff
  src/font/Pretendard-Light.woff
  src/font/Pretendard-Medium.woff
  src/font/Pretendard-Regular.woff
  src/font/Pretendard-SemiBold.woff
  src/font/Pretendard-Thin.woff
  src/font/font.css
  src/fontAwesome.jsx
  src/globalStyles.js
  src/index.js
  src/router/allRouter.js
  src/webpack.config.js
  yarn.lock
Labels: Feature

#25 [BugFix] - 도커 파일 yarn install 수정했습니다.
  Dockerfile-front-prod
Labels: BugFix

#27 [Feature] - 소셜로그인 연결 중입니다.
  src/components/pages/loginPage/loginPage.jsx
Labels: Feature

#28 [Feature] - 소셜 로그인 구현 중입니다.
  src/components/pages/loginPage/loginPage.jsx
Labels: Feature

#29 [Feature] - 로그인 페이지 UI 수정했습니다
  src/asset/image/fastlogin.svg
  src/asset/image/google.svg
  src/asset/image/kakao.svg
  src/asset/image/naver.svg
  src/asset/sass/pages/loginPage/loginPage.scss
  src/components/pages/loginPage/loginPage.jsx
Labels: Feature, UI

#30 [Feature] - 로그인 페이지 UI 수정했습니다
  src/asset/image/fastlogin.svg
  src/asset/image/google.svg
  src/asset/image/kakao.svg
  src/asset/image/naver.svg
  src/asset/sass/pages/loginPage/loginPage.scss
  src/components/pages/loginPage/loginPage.jsx
Labels: Feature, UI

#32 [Feature] - 닉네임, 로그인 페이지 UI 구현했습니다.
  src/asset/image/kakao.svg
  src/asset/image/naver.svg
  src/asset/sass/etc/header/header.scss
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/loginPage/loginPage.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/myPage/myPage.scss
  src/asset/sass/pages/notificationPage/notificationPage.scss
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/fontAwesome.jsx
  src/index.js
  src/router/allRouter.js
Labels: Feature, UI

#37 [Feature] - jwt 토큰 유무 로직 구현했습니다.
  package.json
  src/components/pages/loginPage/constants/index.js
  src/components/pages/loginPage/utils/apiUtil.js
  src/router/allRouter.js
  yarn.lock
Labels: API, Feature

#38 [Feature] - jwt 토큰 유무 로직 구현했습니다.
  package.json
  src/components/pages/loginPage/constants/index.js
  src/components/pages/loginPage/utils/apiUtil.js
  src/router/allRouter.js
  yarn.lock
Labels: API, Feature

#39 [Feature] - 연령대, 성별 태그 UI 및 데이터 전송 로직 구현했습니다.
  src/asset/sass/pages/loginPage/nicknamePage.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/constants/index.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/ui/ageSelection/ageSelection.jsx
  src/components/ui/ageSelection/ageSelection.scss
  src/components/ui/genderSelection/genderSelection.jsx
  src/components/ui/genderSelection/genderSelection.scss
  src/index.js
  src/router/allRouter.js
Labels: API, Feature

#40 [Feature] - 토큰 수신 확인 로직 구현했습니다.
  package.json
  src/asset/sass/etc/tabBar/tabBar.scss
  src/components/global/token/tokenManagement.jsx
  src/router/allRouter.js
  yarn.lock
Labels: API, Feature

#41 [Feature] - 토큰 수신 확인 로직 구현했습니다.
  package.json
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/loginPage/nicknamePage.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/constants/index.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/ui/ageSelection/ageSelection.jsx
  src/components/ui/ageSelection/ageSelection.scss
  src/components/ui/genderSelection/genderSelection.jsx
  src/components/ui/genderSelection/genderSelection.scss
  src/index.js
  src/router/allRouter.js
  yarn.lock
Labels: API, Feature

#42 [Feature] - 라우터 오류 해결했습니다.
  src/router/allRouter.js
Labels: BugFix

#43 [Feature] - 라우터 오류 해결했습니다.
  src/router/allRouter.js
Labels: BugFix

#45 [Feature] - 로그인, 메인 페이지 오류 해결했습니다.
  src/asset/sass/etc/tabBar/tabBar.scss
  src/router/allRouter.js
Labels: BugFix

#46 [Feature] - 로그인, 메인 페이지 오류 해결했습니다.
  src/asset/sass/etc/tabBar/tabBar.scss
  src/router/allRouter.js
Labels: BugFix

#48 [Feature] - 라우터 오류 수정했습니다.
  README.md
Labels: BugFix

#50 [Feature] - 토큰 수신 확인 및 디코딩 구현했습니다.
  .env
  package-lock.json
  package.json
  src/components/global/token/tokenManagement.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/router/allRouter.js
  src/webpack.config.js
  yarn.lock
Labels: API, BugFix, Feature

#51 운영 서버에 배포합니다.
  .env
  package-lock.json
  package.json
  src/components/global/token/tokenManagement.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/router/allRouter.js
  src/webpack.config.js
  yarn.lock
Labels: Feature

#52 [Feature] - 토큰 디코딩 로직 변경했습니다.
  src/components/global/token/tokenManagement.jsx
Labels: BugFix, Feature

#53 운영 서버에 배포합니다.
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#58 [BugFix] - 로그인 페이지 Redirect 오류 수정했습니다.
  src/router/allRouter.js
Labels: BugFix

#59 운영 서버에 배포합니다.
  src/router/allRouter.js
Labels: BugFix

#60 [BugFix] - fetch url 변경했습니다.
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/constants/index.js
  src/components/pages/loginPage/nicknamePage.jsx
Labels: BugFix

#61 운영 서버에 배포합니다.
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/constants/index.js
  src/components/pages/loginPage/nicknamePage.jsx
Labels: BugFix

#62 [BugFix] - api url 수정했습니다.
  src/components/pages/loginPage/nicknamePage.jsx
Labels: API, BugFix

#63 운영 서버에 배포합니다.
  src/components/pages/loginPage/nicknamePage.jsx
Labels: API, BugFix

#65 [Feature] - 로그인 전체 과정 체크합니다.
  package.json
  src/asset/image/loginuser.svg
  src/asset/sass/etc/header/header.scss
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/ui/ageSelection/ageSelection.jsx
  src/components/ui/ageSelection/ageSelection.scss
  src/components/ui/genderSelection/genderSelection.jsx
  src/components/ui/genderSelection/genderSelection.scss
  src/components/ui/header/header.jsx
  yarn.lock
Labels: API, BugFix, UI

#66 운영 서버에 배포합니다.
  .github/workflows/github-actions-front.yml
  Dockerfile-front-dev
  package.json
  src/asset/image/loginuser.svg
  src/asset/sass/etc/header/header.scss
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/ui/ageSelection/ageSelection.jsx
  src/components/ui/ageSelection/ageSelection.scss
  src/components/ui/genderSelection/genderSelection.jsx
  src/components/ui/genderSelection/genderSelection.scss
  src/components/ui/header/header.jsx
  yarn.lock
Labels: API, BugFix, Feature, UI

#68 [BugFix] - 토큰 전송 헤더 수정했습니다.
  package.json
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/ui/modal/modal.jsx
  yarn.lock
Labels: API, BugFix

#69 운영 서버에 배포합니다.
  package.json
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/ui/modal/modal.jsx
  yarn.lock
Labels: API, BugFix

#70 [Feature] - 로그인 전 과정 수정했습니다.
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/ui/header/header.jsx
Labels: API, BugFix, Feature, UI

#71 운영 서버에 배포합니다.
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/ui/header/header.jsx
Labels: BugFix, Feature

#73 [BugFix] - index.js 변수명 수정했습니다.
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/constants/index.js
  src/components/ui/header/header.jsx
Labels: BugFix

#74 운영 서버에 배포합니다.
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/constants/index.js
  src/components/ui/header/header.jsx
Labels: BugFix

#75 [BugFix] - 토큰 확인 로직 수정했습니다.
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/loginPage.jsx
Labels: BugFix

#76 운영 서버에 배포합니다.
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/loginPage.jsx
Labels: BugFix

#77 [BugFix] - 로그인 여부 확인하는 방식 변경했습니다.
  src/components/ui/header/header.jsx
Labels: BugFix

#78 운영 서버에 배포합니다.
  src/components/ui/header/header.jsx
Labels: BugFix

#80 [Feature] - 로그인과 연결되는 페이지 로직 수정했습니다.
  src/asset/sass/etc/header/header.scss
  src/components/pages/myPage/myPage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/ui/header/header.jsx
  src/router/allRouter.js
Labels: BugFix, Feature

#81 운영 서버에 배포합니다.
  src/asset/sass/etc/header/header.scss
  src/components/pages/myPage/myPage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/ui/header/header.jsx
  src/router/allRouter.js
Labels: BugFix, Feature
