Repository Team-Coverflow/Coverflow-FE, pull requests merged in 2024-05, with the labels that each got.

#278 fix : 개발 서버 UI 피드백 반영
  src/asset/sass/etc/question/question.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  yarn.lock
Labels: UI

#280 실시간 알림 기능 및 UI 수정했습니다.
  src/asset/image/notification-answer.svg
  src/asset/image/notification-question.svg
  src/asset/sass/pages/myPage/premiumPage.scss
  src/asset/sass/pages/notificationPage/notificationList.scss
  src/components/global/utils/eventApiUtils.js
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/premiumPage/premiumPage.tsx
  src/components/pages/premiumPage/premiumTicket.tsx
  src/components/ui/banner/bannerImage.scss
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactList.scss
  src/components/ui/contactSlider/contactSlider.jsx
Labels: BugFix, UI

#281 UI 수정 및 로직 수정
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/ui/question/answer.tsx
Labels: Feature, UI

#282 SSE 및 토큰 재발급 로직 수정했습니다.
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/global/utils/eventApiUtils.js
  src/components/global/utils/reissueTokenUtils.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/infoEditPage.tsx
  src/components/pages/myPage/noticePage.tsx
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/pages/termsPage/termsPage.tsx
  src/components/ui/adminSelection/adminPagination.tsx
  src/components/ui/adminSelection/adminSideTap.tsx
  src/components/ui/adminSelection/feedbackSelection.tsx
  src/components/ui/contactSlider/contactList.jsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/question/answerContainer.jsx
Labels: BugFix, Feature, UI

#283 fix : 답변 채택 로직 수정
  src/components/ui/question/answer.tsx
Labels: API, BugFix, Feature

#284 Fix/haseung
  src/asset/image/leaf.svg
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
Labels: UI

#286 UI 스타일 수정했습니다.
  src/App.js
  src/asset/image/yellow-trophy.svg
  src/asset/sass/etc/question/answer.scss
  src/asset/sass/pages/notificationPage/notificationList.scss
  src/asset/sass/pages/notificationPage/notificationPage.scss
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/ui/contactSlider/disclaimer.jsx
  src/components/ui/myPageSelection/myComponent.scss
  src/components/ui/question/answer.tsx
  src/components/ui/searchInput/searchInput.tsx
Labels: BugFix, Feature, UI

#287 UI check list 반영했습니다.
  src/App.js
  src/asset/image/tabbar-new-alert.svg
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/notificationPage/notificationList.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/alertCountUtil.js
  src/components/global/utils/eventApiUtils.js
  src/components/global/utils/reissueTokenUtils.js
  src/components/pages/myPage/feedbackPage.tsx
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/termsPage/termsPage.tsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myComponent.scss
Labels: BugFix, UI

#291 UI check list 반영
  src/asset/image/leaf.svg
  src/asset/image/nature-ecology-tree-3--tree-plant-cloud-shape-park.svg
  src/asset/sass/pages/myPage/noticePage.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/WIL.tsx
  src/components/global/utils/alertCountUtil.js
  src/components/global/utils/apiUtil.js
  src/components/pages/myPage/feedbackPage.tsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/adminSelection/companySelection.scss
  src/components/ui/adminSelection/feedbackSelection.tsx
  src/components/ui/contactSlider/contactList.scss
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/inputbox/TextArea.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myComponent.scss
  src/components/ui/myPageSelection/myQuestion.tsx
  src/components/ui/question/answer.tsx
  src/components/ui/question/question.tsx
Labels: BugFix, Feature, UI

#292 베타 테스트 체크 리스트 수정 중
  src/asset/image/hot.svg
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/etc/question/answer.scss
  src/asset/sass/etc/question/question.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/asset/sass/pages/searchPage/companyRegistPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/pages/searchPage/companyRegistPage.tsx
Labels: BugFix, UI

#293 Fix/beta test haseung
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
Labels: BugFix, Feature, UI

#295 답변 디자인 수정
  package.json
  src/asset/sass/etc/question/answer.scss
  src/components/global/constants/memberOption.ts
  src/components/pages/adminPage/adminMainPage.tsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/ui/adminSelection/companySelection.tsx
  src/components/ui/adminSelection/contactSelection.tsx
  src/components/ui/adminSelection/memberSelection.scss
  src/components/ui/adminSelection/memberSelection.tsx
  src/components/ui/calendar/calendar.tsx
  src/components/ui/question/answer.tsx
  yarn.lock
Labels: Feature, UI

#299 답변 input 창,기업상세 타이틀 및 태그 줄바꿈, 버튼 활성화 수정 및 관리자 CSS 네이밍 수정
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/ui/adminSelection/memberSelection.scss
  src/components/ui/adminSelection/memberSelection.tsx
Labels: BugFix, Feature, UI

#300 질문 상세 페이지, 질문 작성 페이지, 기업 조회 페이지, 데이터 없을 때 화면 UI 추가
  src/asset/image/noContents.svg
  src/asset/sass/etc/noContentsComponent/noContentsComponents.scss
  src/asset/sass/etc/question/answer.scss
  src/asset/sass/etc/question/question.scss
  src/asset/sass/etc/selection/fishTag.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/ui/adminSelection/adminPagination.tsx
  src/components/ui/adminSelection/companySelection.scss
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myQuestion.tsx
  src/components/ui/noContentsComponent/noContentsComponent.tsx
  src/components/ui/question/answer.tsx
  src/components/ui/question/question.tsx
  src/components/ui/selection/fishTag.tsx
  src/store/actions/type.js
  src/store/actions/userActions.js
  src/store/userReducer.js
Labels: API, Feature, UI

#303 UI check list 수정 및 삭제 로직 추가
  src/asset/sass/etc/noContentsComponent/noContentsComponents.scss
  src/asset/sass/pages/notificationPage/notificationPage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/pages/searchPage/searchResultPage.tsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/myPageSelection/myQuestion.tsx
  src/components/ui/noContentsComponent/noContentsComponent.tsx
Labels: API, BugFix, Feature, UI

#304 질문 수정 기능 추가, UI 수정
  src/asset/sass/etc/selection/fishTag.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/ui/question/answer.tsx
Labels: BugFix, Feature, UI

#306 질문 삭제 기능 추가 및 API 요청 핸들러 수정
  src/components/global/utils/apiUtil.js
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/ui/question/answer.tsx
Labels: BugFix

#305 기업관리 유지보수
  src/components/ui/adminSelection/companySelection.tsx
Labels: BugFix, Feature, UI

#308 UI check list 적용
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/postPage/questionWritePage.tsx
Labels: UI

#309 UI check list 적용
  src/components/pages/myPage/myPage.tsx
Labels: UI

#307 질문 상세, 질문 작성 페이지 수정
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/postPage/questionWritePage.tsx
  src/components/ui/question/answer.tsx
Labels: UI

#310 질문 상세 페이지 답변 삭제, 수정 로직 추가했습니다.
  src/components/pages/postPage/questionDetailPage.tsx
Labels: BugFix

#317 회원가입 시 약관동의 페이지로 안 가는 부분 수정 중
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#320 최초 가입 시 토큰 발행 로직 수정했습니다.
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#321 약관 동의 페이지 코드 로직 수정
  src/components/pages/termsPage/termsPage.tsx
Labels: BugFix

#322 약관 동의 페이지 코드 받는 로직 수정
  src/components/global/token/tokenManagement.jsx
Labels: BugFix

#323 정보 입력 페이지 post 요청 수정했습니다.
  src/components/pages/loginPage/nicknamePage.jsx
Labels: BugFix

#324 탈퇴 로직 수정했습니다.
  src/components/global/token/tokenManagement.jsx
  src/components/pages/myPage/secessionPage.tsx
  src/components/pages/termsPage/termsPage.tsx
Labels: BugFix

#325 비회원 상태일 때 기업 등록 안되는 부분 수정
  src/components/pages/searchPage/companyRegistPage.tsx
Labels: BugFix

#330 베타 테스트 중 발생 에러 수정 및 기능 변경
  src/asset/sass/pages/myPage/noticePage.scss
  src/asset/sass/pages/storePage/storePage.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/alertCountUtil.js
  src/components/global/utils/eventApiUtils.js
  src/components/global/utils/reissueTokenUtils.js
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/feedbackPage.tsx
  src/components/pages/myPage/infoEditPage.tsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/myPage/noticePage.tsx
  src/components/pages/notificationPage/notificationList.jsx
  src/components/pages/storePage/storePage.tsx
  src/components/pages/termsPage/termsPage.tsx
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/myPageSelection/myAnswer.tsx
  src/components/ui/question/answerContainer.jsx
Labels: BugFix

#333 UI 개선 사항 적용
  src/asset/sass/pages/myPage/infoEditPage.scss
  src/asset/sass/pages/myPage/noticePage.scss
  src/components/pages/myPage/feedbackPage.tsx
  src/components/pages/myPage/infoEditPage.tsx
  src/components/pages/myPage/noticePage.tsx
  src/components/ui/contactSlider/contactList.scss
  src/components/ui/contactSlider/contactSlider.jsx
  src/components/ui/header/userInfoHeader.jsx
Labels: BugFix, UI

#335 슬래시 공백 제거
  src/components/global/constants/companyOption.ts
Labels: BugFix

#336 검색어 입력 버그 수정
  src/components/ui/searchInput/searchInput.tsx
Labels: BugFix

#337 채택 표시 여부 로직 수정했습니다.
  src/components/pages/myPage/noticePage.tsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/ui/question/answer.tsx
Labels: BugFix

#340 기업 검색 페이지, 질문 관련 페이지 수정
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/ui/question/question.tsx
  src/components/ui/searchInput/searchInput.tsx
Labels: BugFix, Feature

#341 비로그인 상태일 때에서의 UX/UI 변경
  src/components/pages/postPage/questionDetailPage.tsx
Labels: UI

#342 질문 상세 페이지 UI 수정
  src/asset/sass/etc/question/answer.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/components/ui/question/answer.tsx
Labels: BugFix, UI

#343 관리자 공지사항 조회, 생성, 삭제, 수정기능 추가했습니다.
  src/components/pages/adminPage/adminMainPage.tsx
  src/components/ui/adminSelection/companySelection.scss
  src/components/ui/adminSelection/noticeCreate.tsx
  src/components/ui/adminSelection/noticeDetail.tsx
  src/components/ui/adminSelection/noticeSelection.scss
  src/components/ui/adminSelection/noticeSelection.tsx
Labels: API, Feature, UI

#348 관리자페이지 (질문,답변 ) ui 구현 및 api 연결
  src/components/pages/adminPage/adminMainPage.tsx
  src/components/ui/adminSelection/answerSelection.scss
  src/components/ui/adminSelection/answerSelection.tsx
  src/components/ui/adminSelection/questionSelection.scss
  src/components/ui/adminSelection/questionSelection.tsx
  src/components/ui/adminSelection/reportAnswers.scss
  src/components/ui/adminSelection/reportComments.scss
Labels: API, Feature, UI

#350 업종 이상하게 뜨는 부분 수정
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/ui/question/question.tsx
Labels: BugFix, UI

#351 관리자 페이지 필터링 및 모달 api 연결
  src/components/global/constants/adminOption.ts
  src/components/ui/adminSelection/answerSelection.tsx
  src/components/ui/adminSelection/companySelection.tsx
  src/components/ui/adminSelection/memberSelection.scss
  src/components/ui/adminSelection/memberSelection.tsx
  src/components/ui/adminSelection/questionSelection.scss
  src/components/ui/adminSelection/questionSelection.tsx
  src/components/ui/adminSelection/reportAnswers.tsx
  src/components/ui/adminSelection/reportComments.tsx
  src/components/ui/adminSelection/reportQuestions.tsx
  src/components/ui/modal/AnswerModal.tsx
  src/components/ui/modal/ReanswerModal.tsx
  src/components/ui/modal/memberModal.tsx
  src/components/ui/modal/questionModal.tsx
  src/components/ui/modal/recommentModal.tsx
  src/components/ui/modal/requestionModal.tsx
Labels: API, BugFix, Feature, UI

#352 달력 오류 해결 및 날짜 선택 옵션 추가
  src/asset/sass/etc/button/Button.scss
  src/components/ui/adminSelection/answerSelection.tsx
  src/components/ui/adminSelection/contactSelection.tsx
  src/components/ui/adminSelection/memberSelection.tsx
  src/components/ui/adminSelection/questionSelection.tsx
  src/components/ui/adminSelection/reportAnswers.tsx
  src/components/ui/adminSelection/reportComments.tsx
  src/components/ui/adminSelection/reportQuestions.tsx
  src/components/ui/ageSelection/ageSelection.scss
  src/components/ui/calendar/calendar.tsx
Labels: BugFix, Feature

#353 수정 리스트 적용
  src/asset/sass/pages/myPage/infoEditPage.scss
  src/asset/sass/pages/myPage/myPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/adminPage/adminMainPage.tsx
  src/components/pages/myPage/infoEditPage.tsx
  src/components/pages/myPage/myPage.tsx
  src/components/pages/searchPage/companyInfoPage.tsx
  src/components/ui/ageSelection/ageSelection.scss
  src/components/ui/calendar/calendar.tsx
Labels: BugFix, UI

#354 헤더 고정에 따른 스타일 추가
  src/asset/sass/etc/header/titleHeader.scss
  src/asset/sass/etc/tabBar/tabBar.scss
  src/asset/sass/pages/myPage/feedbackPage.scss
  src/asset/sass/pages/myPage/infoEditPage.scss
  src/asset/sass/pages/myPage/myPage.scss
  src/asset/sass/pages/myPage/noticePage.scss
  src/asset/sass/pages/myPage/secessionPage.scss
  src/asset/sass/pages/notificationPage/notificationPage.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/ui/contactSlider/contactSlider.scss
  src/components/ui/header/titleHeader.tsx
  src/components/ui/searchInput/searchInput.tsx
  src/components/ui/tabBar/tabBar.jsx
  src/components/ui/tabBar/tabBar.tsx
  src/styledComponent.js
  src/styledComponent.ts
Labels: UI

#355 헤더 마진 제거에 따른 스타일 추가
  src/asset/sass/etc/header/header.scss
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/loginPage/nicknamePage.scss
  src/asset/sass/pages/myPage/infoEditPage.scss
  src/asset/sass/pages/notificationPage/notificationPage.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/searchPage/companyRegistPage.scss
  src/components/pages/loginPage/loginPage.tsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/postPage/questionDetailPage.tsx
  src/components/pages/searchPage/companyRegistPage.tsx
  src/components/ui/contactSlider/contactSlider.scss
  src/components/ui/searchInput/searchInput.tsx
  src/globalStyles.js
  src/styledComponent.js
  src/styledComponent.ts
Labels: UI
