Repository Team-Coverflow/Coverflow-FE, pull requests merged in 2024-02, with the labels that each got.

#82 [Feature] 모달 구현 중입니다
  package.json
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/ui/button/backButton/backButton.jsx
  src/components/ui/button/startButton/startButton.jsx
  src/components/ui/modal/modals.jsx
  src/components/ui/modal/useModal.js
  src/index.js
  yarn.lock
Labels: Feature

#84 [Feature] - 메인 헤더, 로그아웃 버튼 로직 수정했습니다
  src/asset/image/loginuser.svg
  src/asset/sass/etc/header/header.scss
  src/asset/sass/pages/storePage/storePage.scss
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/storePage/storePage.jsx
  src/components/ui/header/header.jsx
  src/router/allRouter.js
Labels: Feature, UI

#85 운영 서버에 배포합니다.
  .github/workflows/github-actions-front.yml
  package.json
  src/asset/image/loginuser.svg
  src/asset/sass/etc/header/header.scss
  src/asset/sass/pages/storePage/storePage.scss
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/storePage/storePage.jsx
  src/components/ui/button/backButton/backButton.jsx
  src/components/ui/button/startButton/startButton.jsx
  src/components/ui/header/header.jsx
  src/components/ui/modal/modals.jsx
  src/components/ui/modal/useModal.js
  src/index.js
  src/router/allRouter.js
  yarn.lock
Labels: BugFix, Feature, UI

#87 [Feature] - 메인페이지 헤더 UI 기능 구현했습니다.
  src/asset/image/loginuser.svg
  src/asset/image/reward.svg
  src/asset/sass/etc/header/header.scss
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/constants/index.js
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/storePage/storePage.jsx
  src/components/ui/header/header.jsx
  src/router/allRouter.js
Labels: API, Feature, UI

#92 [Bugfix] className 수정
  src/asset/sass/pages/myPage/myPage.scss
  src/components/pages/myPage/myPage.jsx
Labels: BugFix

#96 [BugFix] 콘솔 입력 및 라우터 토큰 주석 처리
  src/components/pages/searchPage/searchPage.jsx
  src/router/allRouter.js
Labels: BugFix, Test

#97 [BugFix] API 로직 수정했습니다.
  src/asset/sass/etc/header/userInfoHeader.scss
  src/components/global/token/tokenManagement.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/pages/searchPage/searchPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/header/titleHeader.jsx
  src/components/ui/header/userInfoHeader.jsx
Labels: API, BugFix

#100 (24/02/14 - 1) 프로덕션 배포합니다.
  .dockerignore
  Dockerfile-front-dev
  Dockerfile-front-prod
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/pages/searchPage/companyRegistPage.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/global/constants/index.js
  src/components/global/token/tokenManagement.jsx
  src/components/global/utils/apiUtil.js
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/loginPage/nicknamePage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/notificationPage/notificationPage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/pages/searchPage/searchPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/pages/storePage/storePage.jsx
  src/components/ui/header/titleHeader.jsx
  src/components/ui/header/userInfoHeader.jsx
  src/components/ui/tabBar/tabBar.jsx
  src/router/allRouter.js
Labels: Feature

#105 [Feature] 검색 - 기업 목록 - 질문 - 질문 등록 페이지 API 연결
  package.json
  src/asset/sass/etc/question/question.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/question/question.jsx
  src/components/ui/searchInput/searchInput.jsx
Labels: API, Feature, UI

#106 [Feature] 코드 오류 수정
  src/asset/image/warning.svg
  src/asset/sass/etc/searchInput/searchInput.scss
  src/components/pages/myPage/contactPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/ui/searchInput/searchInput.jsx
  src/router/allRouter.js
Labels: API, BugFix, Test

#107 [BugFix] API 로직 오류 수정
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
Labels: API, BugFix

#108 [Bugfix] API 키값 수정했습니다.
  src/components/pages/searchPage/searchResultPage.jsx
Labels: API, BugFix

#109 [BugFix] API 로직 수정
  src/components/pages/searchPage/searchResultPage.jsx
Labels: API, BugFix

#110 fix: 검색 수정 중입니다.
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/searchInput/searchInput.jsx
Labels: BugFix

#111 fix: useLocation 추가했습니다.
  src/components/pages/searchPage/searchResultPage.jsx
Labels: BugFix

#113 fix: 검색 수정합니다.
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/searchInput/searchInput.jsx
Labels: BugFix

#114 [Bugfix] - 기업 검색 API 로직 & UI 수정
  package.json
  src/App.css
  src/asset/sass/etc/question/question.scss
  src/asset/sass/etc/searchInput/searchInput.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/asset/sass/pages/myPage/secessionPage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/pages/myPage/secessionPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/searchPage.jsx
  src/components/pages/searchPage/searchResultPage.jsx
  src/components/ui/question/question.jsx
  src/components/ui/searchInput/searchInput.jsx
  src/globalStyles.js
  src/router/allRouter.js
  src/styledComponent.js
Labels: API, BugFix, UI

#116 [Bugfix] 기업 등록 페이지 수정
  src/components/pages/searchPage/companyRegistPage.jsx
  src/index.js
Labels: API, BugFix

#117 [Bugfix] 기업 등록 페이지 내 토큰 제거했습니다.
  src/components/pages/searchPage/companyRegistPage.jsx
Labels: BugFix

#118 [Buf
  src/components/pages/postPage/questionWritePage.jsx
  src/router/allRouter.js
Labels: API, BugFix

#119 [Bugfix] API 연결 로직 수정했습니다.
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
Labels: API, BugFix

#120 [Bugfix] API 로직 수정했습니다.
  src/components/pages/postPage/questionWritePage.jsx
Labels: API, BugFix

#121 [Feature] 기업 등록 페이지 UI 수정
  package.json
  src/asset/image/kakao.svg
  src/asset/sass/etc/question/question.scss
  src/asset/sass/pages/loginPage/loginPage.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/asset/sass/pages/searchPage/companyRegistPage.scss
  src/components/pages/loginPage/loginPage.jsx
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/pages/searchPage/companyRegistPage.jsx
  src/components/ui/question/question.jsx
  src/components/ui/searchInput/searchInput.jsx
  src/globalStyles.js
  src/router/allRouter.js
Labels: API, BugFix, UI

#122 개발 서버에 배포합니다.
  package.json
  src/router/allRouter.js
Labels: BugFix

#123 [Feature] 답변, 회원탈퇴 api 로직 수정했습니다.
  src/components/pages/myPage/myPage.jsx
  src/components/pages/myPage/secessionPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  yarn.lock
Labels: API, BugFix, Test

#125 [Bugfix] 닉네임 변경, 회원탈퇴 로직 수정했습니다.
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/secessionPage.jsx
  src/globalStyles.js
  src/styledComponent.js
Labels: API, BugFix

#126 [Bugfix] API 테스트 중입니다.
  src/asset/sass/etc/header/userInfoHeader.scss
  src/asset/sass/etc/question/question.scss
  src/asset/sass/pages/mainPage/mainPage.scss
  src/components/pages/mainPage/mainPage.jsx
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/myPage/secessionPage.jsx
  src/globalStyles.js
  src/styledComponent.js
Labels: API, BugFix

#127 API 테스트 중입니다.
  src/components/pages/myPage/infoEditPage.jsx
Labels: API, BugFix

#131 [Feature] 페이지 UI 구현 및 수정 중입니다.
  package.json
  src/asset/image/questitle.svg
  src/asset/image/report.svg
  src/asset/sass/etc/question/question.scss
  src/asset/sass/etc/selection/fishTag.scss
  src/asset/sass/etc/selection/secessionSelection.scss
  src/asset/sass/pages/adminPage/adminMainPage.scss
  src/asset/sass/pages/myPage/infoEditPage.scss
  src/asset/sass/pages/myPage/myPage.scss
  src/asset/sass/pages/myPage/secessionPage.scss
  src/asset/sass/pages/postPage/questionDetailPage.scss
  src/asset/sass/pages/postPage/questionWritePage.scss
  src/asset/sass/pages/searchPage/companyInfoPage.scss
  src/asset/sass/pages/searchPage/searchResultPage.scss
  src/components/pages/adminPage/adminMainPage.jsx
  src/components/pages/myPage/infoEditPage.jsx
  src/components/pages/myPage/myPage.jsx
  src/components/pages/postPage/questionDetailPage.jsx
  src/components/pages/postPage/questionWritePage.jsx
  src/components/pages/searchPage/companyInfoPage.jsx
  src/components/ui/question/answer.jsx
  src/components/ui/question/question.jsx
  src/components/ui/selection/fishTag.jsx
  src/components/ui/selection/secessionSelection.jsx
  src/router/allRouter.js
Labels: BugFix, Feature, UI
